language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: "9.6" # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "chrischindevapp-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy:
  - npm run build-client # make the bundle
  # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: chrischindevapp
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: 9U3wtewkKa6lmPaxeVP7okaV7WEb7KvU8Gq+vB7GyeNXtLmTFUFBC/cbmhiDH14spOvwBFHtZGOwer7jp8ivAFGF5qnkU3oM9kH4dF9chkcZqbf1hsk5tUmWWIGddlAwwoQAF+c1kylWKCeYRivyLMx10P9rpxIZ27dhan1rBCO9IHy/R7TKmcDR4gtNLvEjz9gjyWCncoQkQuyVMP/LNK6e/2+kOQZzJwgZjKH6A/D+99PQZr+bqlLCsiuADZHMRmRzQCVyDua9tqbJQVpIWCYo60vmzdyS8H6EROOFuvl5InoBOIq6xBFIHIwO5C8xxZzvBNCeJ3MuCbZa30sse9I4Lxfs8XqJg5IQjtQunQIcm6MVg+6l//sWKf26IhYBbYDnFs+HOKge9JIFnsI8x78s8GVWiabSyOOLk2X9u3CNc3GASFQRMJXUTgVRigScakxQFB4IG8d/hfHxgtOnjcEDPNcfsCWEsgH4KJ9k2gIpnQARnlhv2b4G0uM5KWqtF0umwsNj9yLFZZHrYlt1j3vmimpM63m4A+e9WMud5NSMhhXOCsKGIA4kO6uFGUflMO5vOlvahZN2dXWhyUIIy5MBxfp0qXGvtF3XD/d1c/fnOgXDsoU/Rp2QoCguw3YuLNKE9pidef4uYhSEGvABC5ZAWiRcY0WTnay6y8rpzbE=
